version: '3.8'
services:
  db:
    container_name: anylistDB
    image: postgres:14.3
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - data_anylist:/var/lib/postgresql/data
volumes:
  data_anylist: